name: neutron_net

channels:
    - pytorch
    - conda-forge
    - defaults

dependencies:
    - jupyter_client=5.2.3
    - jupyter_core=4.4.0
    - nb_conda=2.2.1
    - nb_conda_kernels=2.1.1
    - notebook=5.7.0
    - numba=0.40.0
    - numpy=1.15.4
    - python=3.6.6
    - scipy=1.1.0
    - matplotlib=3.0.0
    - mkl=2018.0.3
    - pytorch=0.4.1
